package assets_test

import (
	"context"
	"errors"
	"testing"

	"github.com/google/uuid"
	"github.com/hcai-chat/hcai-chat/internal/assets"
	"github.com/hcai-chat/hcai-chat/internal/community"
)

func TestSavedWorksRemainReferenceOnlyAndRespectVisibility(t *testing.T) {
	pool, cleanup := assetTestPool(t)
	defer cleanup()
	ctx := context.Background()
	authorID, viewerID, outsiderID := uuid.New(), uuid.New(), uuid.New()
	if _, err := pool.Exec(ctx, `
		INSERT INTO users(id,email,handle,display_name,role,status) VALUES
		($1,$2,$3,'Saved Work Author','creator','active'),
		($4,$5,$6,'Saved Work Viewer','member','active'),
		($7,$8,$9,'Saved Work Outsider','member','active')`,
		authorID, authorID.String()+"@test.local", "author_"+authorID.String()[:8],
		viewerID, viewerID.String()+"@test.local", "viewer_"+viewerID.String()[:8],
		outsiderID, outsiderID.String()+"@test.local", "outsider_"+outsiderID.String()[:8]); err != nil {
		t.Fatal(err)
	}
	assetID, workID, postID := uuid.New(), uuid.New(), uuid.New()
	if _, err := pool.Exec(ctx, `
		INSERT INTO assets(id,owner_id,kind,title,media_url,mime_type,width,height,scan_status,source_type,license_code)
		VALUES($1,$2,'image','Saved source','/media/saved-source.jpg','image/jpeg',1200,900,'clean','delivery','personal')`, assetID, authorID); err != nil {
		t.Fatal(err)
	}
	if _, err := pool.Exec(ctx, `
		INSERT INTO works(id,author_id,asset_id,title,summary,prompt_visibility,model_name,status,ai_disclosure,published_at)
		VALUES($1,$2,$3,'Saved reference','A published reference work.','partial','Local Test','published','Generated by the deterministic Local Test provider.',now())`, workID, authorID, assetID); err != nil {
		t.Fatal(err)
	}
	if _, err := pool.Exec(ctx, `
		INSERT INTO posts(id,author_id,work_id,body,status,published_at)
		VALUES($1,$2,$3,'Saved reference post','published',now())`, postID, authorID, workID); err != nil {
		t.Fatal(err)
	}

	reactions := community.NewRepository(pool)
	service := assets.NewService(pool, t.TempDir())
	for attempt := 0; attempt < 2; attempt++ {
		state, err := reactions.SetReaction(ctx, viewerID, postID, "bookmark", true)
		if err != nil || !state.ViewerBookmarked || state.BookmarkCount != 1 {
			t.Fatalf("save attempt %d: %#v %v", attempt+1, state, err)
		}
	}
	items, err := service.ListSavedWorks(ctx, viewerID, assets.ListInput{})
	if err != nil || len(items.Items) != 1 || items.Items[0].PostID != postID || items.Items[0].WorkID != workID || items.Items[0].AssetID != assetID || items.Items[0].PromptVisibility != "partial" {
		t.Fatalf("saved projection mismatch: %#v %v", items, err)
	}
	if outsider, err := service.ListSavedWorks(ctx, outsiderID, assets.ListInput{}); err != nil || len(outsider.Items) != 0 {
		t.Fatalf("outsider saw another account's saves: %#v %v", outsider, err)
	}
	if owned, err := service.List(ctx, viewerID, assets.ListInput{}); err != nil || len(owned.Items) != 0 {
		t.Fatalf("bookmark entered owned Assets: %#v %v", owned, err)
	}
	if _, err := service.GetOwned(ctx, viewerID, assetID); !errors.Is(err, assets.ErrForbidden) {
		t.Fatalf("bookmark bypassed Asset ownership: %v", err)
	}

	if _, err := pool.Exec(ctx, `UPDATE works SET status='hidden' WHERE id=$1`, workID); err != nil {
		t.Fatal(err)
	}
	if hidden, err := service.ListSavedWorks(ctx, viewerID, assets.ListInput{}); err != nil || len(hidden.Items) != 0 {
		t.Fatalf("hidden work remained in saved projection: %#v %v", hidden, err)
	}
	if _, err := pool.Exec(ctx, `UPDATE works SET status='published' WHERE id=$1`, workID); err != nil {
		t.Fatal(err)
	}
	if restored, err := service.ListSavedWorks(ctx, viewerID, assets.ListInput{}); err != nil || len(restored.Items) != 1 {
		t.Fatalf("restored work did not return: %#v %v", restored, err)
	}
	if _, err := reactions.SetReaction(ctx, viewerID, postID, "bookmark", false); err != nil {
		t.Fatal(err)
	}
	if removed, err := service.ListSavedWorks(ctx, viewerID, assets.ListInput{}); err != nil || len(removed.Items) != 0 {
		t.Fatalf("unsaved work remained: %#v %v", removed, err)
	}
}
