package creation_test

import (
	"context"
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"os"
	"os/exec"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/hcai-chat/hcai-chat/internal/accountlifecycle"
	"github.com/hcai-chat/hcai-chat/internal/creation"
	"github.com/hcai-chat/hcai-chat/internal/datarights"
	"github.com/hcai-chat/hcai-chat/internal/generationoutput"
	"github.com/hcai-chat/hcai-chat/internal/identity"
	"github.com/hcai-chat/hcai-chat/internal/observability"
	"github.com/hcai-chat/hcai-chat/internal/platform/database"
	"github.com/hcai-chat/hcai-chat/internal/platform/jobs"
	"github.com/hcai-chat/hcai-chat/internal/platform/media"
	"github.com/hcai-chat/hcai-chat/internal/testutil"
	"github.com/jackc/pgx/v5/pgxpool"
)

type outputFaultStore struct {
	media.Store
	afterPut        func() error
	deleteError     bool
	deleteHook      func(context.Context) error
	acknowledgeOnly bool
	deletes         atomic.Int64
}

func (s *outputFaultStore) Put(ctx context.Context, key string, body []byte, mime string) error {
	if err := s.Store.Put(ctx, key, body, mime); err != nil {
		return err
	}
	if s.afterPut != nil {
		return s.afterPut()
	}
	return nil
}
func (s *outputFaultStore) Delete(ctx context.Context, key string) error {
	s.deletes.Add(1)
	if s.deleteHook != nil {
		return s.deleteHook(ctx)
	}
	if s.deleteError {
		return errors.New("private storage failure")
	}
	if s.acknowledgeOnly {
		return nil
	}
	return s.Store.Delete(ctx, key)
}

func outputIntentFor(t *testing.T, pool *pgxpool.Pool, id uuid.UUID) (uuid.UUID, string, string) {
	t.Helper()
	var intent uuid.UUID
	var key, state string
	if err := pool.QueryRow(context.Background(), `SELECT id,storage_key,status FROM generation_output_writes WHERE generation_id=$1 ORDER BY created_at,id LIMIT 1`, id).Scan(&intent, &key, &state); err != nil {
		t.Fatal(err)
	}
	return intent, key, state
}
func makeOutputDue(t *testing.T, pool *pgxpool.Pool, id uuid.UUID) {
	t.Helper()
	if _, err := pool.Exec(context.Background(), `UPDATE generation_output_writes SET next_check_at=now()-interval '1 second' WHERE id=$1`, id); err != nil {
		t.Fatal(err)
	}
}

// This helper is launched only by the crash regression below. Exit at the
// irreversible boundary without running defers, just as a dead worker would.
func TestGenerationOutputCrashChild(t *testing.T) {
	if os.Getenv("HCAI_OUTPUT_CRASH_CHILD") != "1" {
		t.Skip("subprocess helper")
	}
	ctx := context.Background()
	pool, err := database.Open(ctx, os.Getenv("HCAI_OUTPUT_CRASH_DSN"))
	if err != nil {
		t.Fatal("open isolated child database", err)
	}
	store := &outputFaultStore{Store: media.NewLocalStore(os.Getenv("HCAI_OUTPUT_CRASH_ROOT")), afterPut: func() error { os.Exit(88); return nil }}
	svc := creation.NewServiceWithMedia(pool, media.NewCatalog(store), creation.NewLocalRuntimeCatalog(os.Getenv("HCAI_OUTPUT_CRASH_IMAGE"), true))
	id, err := uuid.Parse(os.Getenv("HCAI_OUTPUT_CRASH_GENERATION"))
	if err != nil {
		t.Fatal(err)
	}
	if err = svc.HandleJob(ctx, lifecycleJob(t, pool, id)); err != nil {
		t.Fatal(err)
	}
	t.Fatal("child did not reach output write")
}

func TestGenerationOutputProcessCrashLeavesRecoverableIntent(t *testing.T) {
	pool, cleanup := testPool(t)
	defer cleanup()
	ctx := context.Background()
	owner := lifecycleOwner(t, pool)
	root := t.TempDir()
	source := root + "/provider.jpg"
	if err := os.WriteFile(source, []byte("durable generated bytes"), 0600); err != nil {
		t.Fatal(err)
	}
	svc := creation.NewService(pool, root, source, true)
	g, err := svc.SubmitCommand(ctx, owner, creation.SubmitInput{Mode: "image", Prompt: "Crash recovery reference"}, "crash-output-intent", "test")
	if err != nil {
		t.Fatal(err)
	}
	executable, err := os.Executable()
	if err != nil {
		t.Fatal(err)
	}
	childCtx, cancelChild := context.WithTimeout(ctx, 30*time.Second)
	defer cancelChild()
	child := exec.CommandContext(childCtx, executable, "-test.run=^TestGenerationOutputCrashChild$")
	child.Env = append(os.Environ(), "HCAI_OUTPUT_CRASH_CHILD=1", "HCAI_OUTPUT_CRASH_DSN="+pool.Config().ConnString(), "HCAI_OUTPUT_CRASH_ROOT="+root, "HCAI_OUTPUT_CRASH_IMAGE="+source, "HCAI_OUTPUT_CRASH_GENERATION="+g.ID.String())
	result, err := child.CombinedOutput()
	var exited *exec.ExitError
	if !errors.As(err, &exited) || exited.ExitCode() != 88 {
		t.Fatalf("child result %v: %s", err, result)
	}
	intent, key, state := outputIntentFor(t, pool, g.ID)
	if state != "pending" {
		t.Fatal(state)
	}
	store := media.NewLocalStore(root)
	if _, err = store.Stat(ctx, key); err != nil {
		t.Fatal("file not written before crash", err)
	}
	var assets, charges, reserved int
	if err = pool.QueryRow(ctx, `SELECT (SELECT count(*) FROM assets WHERE source_id=$1),(SELECT count(*) FROM point_entries WHERE operation_id=$1 AND entry_type='generation_charge'),(SELECT reserved_points FROM point_accounts WHERE user_id=$2)`, g.ID, owner).Scan(&assets, &charges, &reserved); err != nil || assets != 0 || charges != 0 || reserved <= 0 {
		t.Fatalf("crash committed result: %d %d %d %v", assets, charges, reserved, err)
	}
	// Recover the abandoned real attempt before another worker claims the retry.
	expireGenerationJob(t, pool, lifecycleJob(t, pool, g.ID))
	// A real retry may generate different bytes; its unique intent must not reuse
	// or destroy the abandoned file or capture more than one final charge.
	if err = os.WriteFile(source, []byte("second independently generated result"), 0600); err != nil {
		t.Fatal(err)
	}
	if err = svc.HandleJob(ctx, lifecycleJob(t, pool, g.ID)); err != nil {
		t.Fatal(err)
	}
	var attachedKey string
	if err = pool.QueryRow(ctx, `SELECT storage_key FROM generation_output_writes WHERE generation_id=$1 AND status='attached'`, g.ID).Scan(&attachedKey); err != nil || attachedKey == key {
		t.Fatalf("retry reused old intent: %q %v", attachedKey, err)
	}
	makeOutputDue(t, pool, intent)
	sweeper := generationoutput.NewService(pool, media.NewCatalog(store))
	if n, err := sweeper.Reconcile(ctx, 100); err != nil || n != 1 {
		t.Fatal(n, err)
	}
	if _, err = store.Stat(ctx, key); !errors.Is(err, media.ErrNotFound) {
		t.Fatal("abandoned output remains", err)
	}
	if _, err = store.Stat(ctx, attachedKey); err != nil {
		t.Fatal("attached output deleted", err)
	}
	if err = svc.HandleJob(ctx, lifecycleJob(t, pool, g.ID)); err != nil {
		t.Fatal(err)
	}
	if err = pool.QueryRow(ctx, `SELECT count(*) FROM point_entries WHERE operation_id=$1 AND entry_type='generation_charge'`, g.ID).Scan(&charges); err != nil || charges != 1 {
		t.Fatal("duplicate charge", charges, err)
	}
}

// Read backend frames so the connection can drop only COMMIT's successful
// response. The server has committed, while pgx observes an I/O failure.
type commitReplyDropConn struct {
	net.Conn
	armed, dropped *atomic.Bool
	pending        []byte
}

func (c *commitReplyDropConn) Read(p []byte) (int, error) {
	if len(p) == 0 {
		return 0, nil
	}
	if len(c.pending) == 0 {
		var header [5]byte
		if _, err := io.ReadFull(c.Conn, header[:]); err != nil {
			return 0, err
		}
		length := int(binary.BigEndian.Uint32(header[1:]))
		if length < 4 || length > 16*1024*1024 {
			return 0, fmt.Errorf("invalid database test frame")
		}
		frame := make([]byte, length+1)
		copy(frame, header[:])
		if _, err := io.ReadFull(c.Conn, frame[5:]); err != nil {
			return 0, err
		}
		if frame[0] == 'C' && string(frame[5:]) == "COMMIT\x00" && c.armed.CompareAndSwap(true, false) {
			c.dropped.Store(true)
			_ = c.Conn.Close()
			return 0, io.ErrUnexpectedEOF
		}
		c.pending = frame
	}
	n := copy(p, c.pending)
	c.pending = c.pending[n:]
	return n, nil
}

func TestGenerationOutputLostCommitReplyPreservesCommittedAsset(t *testing.T) {
	pool, cleanup := testPool(t)
	defer cleanup()
	ctx := context.Background()
	owner := lifecycleOwner(t, pool)
	var armed, dropped atomic.Bool
	config := pool.Config()
	config.MinConns = 0
	config.ConnConfig.DialFunc = func(ctx context.Context, network, address string) (net.Conn, error) {
		c, err := (&net.Dialer{}).DialContext(ctx, network, address)
		if err != nil {
			return nil, err
		}
		return &commitReplyDropConn{Conn: c, armed: &armed, dropped: &dropped}, nil
	}
	faultyPool, err := pgxpool.NewWithConfig(ctx, config)
	if err != nil {
		t.Fatal(err)
	}
	defer faultyPool.Close()
	store := &outputFaultStore{Store: media.NewLocalStore(t.TempDir()), afterPut: func() error { armed.Store(true); return nil }}
	svc := creation.NewServiceWithMedia(faultyPool, media.NewCatalog(store), creation.NewRuntimeCatalog(newLifecycleRuntime(t)))
	g, err := svc.SubmitCommand(ctx, owner, creation.SubmitInput{Mode: "image", Prompt: "Commit response loss"}, "commit-response-loss", "test")
	if err != nil {
		t.Fatal(err)
	}
	if err = svc.HandleJob(ctx, lifecycleJob(t, pool, g.ID)); err != nil {
		t.Fatal(err)
	}
	if !dropped.Load() {
		t.Fatal("no successful commit reply was dropped")
	}
	_, key, state := outputIntentFor(t, pool, g.ID)
	if state != "attached" || store.deletes.Load() != 0 {
		t.Fatalf("committed output cleanup: %s deletes=%d", state, store.deletes.Load())
	}
	if _, err = store.Stat(ctx, key); err != nil {
		t.Fatal("committed bytes missing", err)
	}
	if n, err := generationoutput.NewService(pool, media.NewCatalog(store)).Reconcile(ctx, 100); err != nil || n != 0 {
		t.Fatal(n, err)
	}
	var stateNow string
	var charges, notices int
	if err = pool.QueryRow(ctx, `SELECT status,(SELECT count(*) FROM point_entries WHERE operation_id=$1 AND entry_type='generation_charge'),(SELECT count(*) FROM notifications WHERE resource_id=$1 AND kind='generation.completed') FROM generations WHERE id=$1`, g.ID).Scan(&stateNow, &charges, &notices); err != nil || stateNow != "succeeded" || charges != 1 || notices != 1 {
		t.Fatalf("commit not atomic: %s %d %d %v", stateNow, charges, notices, err)
	}
}

func TestGenerationOutputAmbiguousWriteAndRollbackAreTracked(t *testing.T) {
	pool, cleanup := testPool(t)
	defer cleanup()
	ctx := context.Background()
	for _, scenario := range []string{"put_reply_lost", "result_commit_rejected"} {
		t.Run(scenario, func(t *testing.T) {
			owner := lifecycleOwner(t, pool)
			store := &outputFaultStore{Store: media.NewLocalStore(t.TempDir())}
			catalog := media.NewCatalog(store)
			if scenario == "put_reply_lost" {
				store.afterPut = func() error { return errors.New("write response lost") }
			} else {
				if _, err := pool.Exec(ctx, `CREATE FUNCTION reject_output_commit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected result commit failure'; END $$;
    CREATE CONSTRAINT TRIGGER reject_output_commit AFTER INSERT ON notifications DEFERRABLE INITIALLY DEFERRED FOR EACH ROW WHEN(NEW.kind='generation.completed') EXECUTE FUNCTION reject_output_commit()`); err != nil {
					t.Fatal(err)
				}
			}
			svc := creation.NewServiceWithMedia(pool, catalog, creation.NewRuntimeCatalog(newLifecycleRuntime(t)))
			g, err := svc.SubmitCommand(ctx, owner, creation.SubmitInput{Mode: "image", Prompt: "Tracked output failure"}, "tracked-output-failure", "test")
			if err != nil {
				t.Fatal(err)
			}
			job := lifecycleJob(t, pool, g.ID)
			job = testutil.FinalGenerationAttempt(t, pool, job)
			if err = svc.HandleJob(ctx, job); err == nil {
				t.Fatal("expected persistence failure")
			}
			intent, key, state := outputIntentFor(t, pool, g.ID)
			if state != "pending" || store.deletes.Load() != 0 {
				t.Fatalf("uncertain result deleted: %s %d", state, store.deletes.Load())
			}
			var assets, charges, reserved int
			if err = pool.QueryRow(ctx, `SELECT (SELECT count(*) FROM assets WHERE source_id=$1),(SELECT count(*) FROM point_entries WHERE operation_id=$1 AND entry_type='generation_charge'),(SELECT reserved_points FROM point_accounts WHERE user_id=$2)`, g.ID, owner).Scan(&assets, &charges, &reserved); err != nil || assets != 0 || charges != 0 || reserved != 0 {
				t.Fatalf("failed result committed: %d %d %d %v", assets, charges, reserved, err)
			}
			if scenario == "result_commit_rejected" {
				if _, err = pool.Exec(ctx, `DROP TRIGGER reject_output_commit ON notifications`); err != nil {
					t.Fatal(err)
				}
			}
			makeOutputDue(t, pool, intent)
			store.deleteError = true
			sweeper := generationoutput.NewService(pool, catalog)
			if _, err = sweeper.Reconcile(ctx, 100); err == nil {
				t.Fatal("cleanup failure hidden")
			}
			var code string
			if err = pool.QueryRow(ctx, `SELECT last_error_code FROM generation_output_writes WHERE id=$1`, intent).Scan(&code); err != nil || code != "generation_output_cleanup_failed" {
				t.Fatal(code, err)
			}
			store.deleteError = false
			store.acknowledgeOnly = true
			makeOutputDue(t, pool, intent)
			if _, err = sweeper.Reconcile(ctx, 100); err == nil {
				t.Fatal("Delete acknowledgement treated as erasure")
			}
			store.acknowledgeOnly = false
			makeOutputDue(t, pool, intent)
			if _, err = sweeper.Reconcile(ctx, 100); err != nil {
				t.Fatal(err)
			}
			if _, err = store.Stat(ctx, key); !errors.Is(err, media.ErrNotFound) {
				t.Fatal("unattached file not removed", err)
			}
			// A remote PUT can finish after its original caller has timed out. Retired
			// locations remain tracked and are periodically checked again.
			if err = store.Store.Put(ctx, key, []byte("isolated lifecycle fixture"), "image/jpeg"); err != nil {
				t.Fatal(err)
			}
			makeOutputDue(t, pool, intent)
			if _, err = sweeper.Reconcile(ctx, 100); err != nil {
				t.Fatal(err)
			}
			if _, err = store.Stat(ctx, key); !errors.Is(err, media.ErrNotFound) {
				t.Fatal("late write escaped tombstone recheck", err)
			}
			if _, err = pool.Exec(ctx, `UPDATE generation_output_writes SET status='pending',verified_absent_at=NULL WHERE id=$1`, intent); err == nil {
				t.Fatal("retired intent revived")
			}
		})
	}
}

func TestGenerationOutputDeletionIncludesUnattachedLocations(t *testing.T) {
	pool, cleanup := testPool(t)
	defer cleanup()
	ctx := context.Background()
	root := t.TempDir()
	store := &outputFaultStore{Store: media.NewLocalStore(root), afterPut: func() error { return errors.New("lost storage response") }}
	catalog := media.NewCatalog(store)
	deletion := datarights.NewServiceWithMedia(pool, root, catalog)
	owner, deleteJob := lifecycleDeletion(t, ctx, pool, deletion)
	svc := creation.NewServiceWithMedia(pool, catalog, creation.NewRuntimeCatalog(newLifecycleRuntime(t)))
	g, err := svc.SubmitCommand(ctx, owner, creation.SubmitInput{Mode: "image", Prompt: "Unattached private result"}, "unattached-delete-test", "test")
	if err != nil {
		t.Fatal(err)
	}
	job := lifecycleJob(t, pool, g.ID)
	job = testutil.FinalGenerationAttempt(t, pool, job)
	if err = svc.HandleJob(ctx, job); err == nil {
		t.Fatal("missing write error")
	}
	_, key, state := outputIntentFor(t, pool, g.ID)
	if state != "pending" {
		t.Fatal(state)
	}
	store.deleteError = true
	if err = deletion.HandleDeletionJob(ctx, deleteJob); err == nil {
		t.Fatal("deletion completed without cleanup")
	}
	var receipts int
	if err = pool.QueryRow(ctx, `SELECT count(*) FROM data_rights_deletion_receipts r JOIN data_rights_requests q ON q.id=r.request_id WHERE q.user_id=$1`, owner).Scan(&receipts); err != nil || receipts != 0 {
		t.Fatal(receipts, err)
	}
	store.deleteError = false
	if err = deletion.HandleDeletionJob(ctx, deleteJob); err != nil {
		t.Fatal(err)
	}
	assertDeletedGeneration(t, ctx, pool, owner, g.ID, "failed")
	if _, err = store.Stat(ctx, key); !errors.Is(err, media.ErrNotFound) {
		t.Fatal("private uncommitted file survived deletion", err)
	}
}

func TestGenerationOutputCleanupHonorsHoldAndRejectsChangedBytes(t *testing.T) {
	pool, cleanup := testPool(t)
	defer cleanup()
	ctx := context.Background()
	owner := lifecycleOwner(t, pool)
	store := &outputFaultStore{Store: media.NewLocalStore(t.TempDir()), afterPut: func() error { return errors.New("lost storage response") }}
	catalog := media.NewCatalog(store)
	svc := creation.NewServiceWithMedia(pool, catalog, creation.NewRuntimeCatalog(newLifecycleRuntime(t)))
	g, err := svc.SubmitCommand(ctx, owner, creation.SubmitInput{Mode: "image", Prompt: "Retained uncommitted result"}, "retained-output-test", "test")
	if err != nil {
		t.Fatal(err)
	}
	job := lifecycleJob(t, pool, g.ID)
	job = testutil.FinalGenerationAttempt(t, pool, job)
	if err = svc.HandleJob(ctx, job); err == nil {
		t.Fatal("expected write failure")
	}
	intent, key, _ := outputIntentFor(t, pool, g.ID)
	actor := lifecycleOwner(t, pool)
	if _, err = pool.Exec(ctx, `UPDATE users SET role='admin' WHERE id=$1`, actor); err != nil {
		t.Fatal(err)
	}
	deletion := datarights.NewServiceWithMedia(pool, t.TempDir(), catalog)
	hold, err := deletion.CreateHold(ctx, actor, datarights.HoldInput{UserID: owner, AuthorityReference: "RETAIN-GENERATION-EVIDENCE"}, "hold")
	if err != nil {
		t.Fatal(err)
	}
	makeOutputDue(t, pool, intent)
	sweeper := generationoutput.NewService(pool, catalog)
	if n, err := sweeper.Reconcile(ctx, 100); err != nil || n != 1 {
		t.Fatal(n, err)
	}
	if store.deletes.Load() != 0 {
		t.Fatal("legal hold bypassed")
	}
	if _, err = deletion.ReleaseHold(ctx, actor, hold.ID); err != nil {
		t.Fatal(err)
	}
	if err = store.Store.Delete(ctx, key); err != nil {
		t.Fatal(err)
	}
	if err = store.Store.Put(ctx, key, []byte("different unrecognized bytes"), "image/jpeg"); err != nil {
		t.Fatal(err)
	}
	makeOutputDue(t, pool, intent)
	if _, err = sweeper.Reconcile(ctx, 100); !errors.Is(err, generationoutput.ErrReferenced) {
		t.Fatal("unrecognized bytes not protected", err)
	}
	if store.deletes.Load() != 0 {
		t.Fatal("unexpected content deleted")
	}
	// Restore the exact recorded bytes, then concurrent scanners clean once and
	// retain one location record. Account locks prevent races with other writers.
	if err = store.Store.Delete(ctx, key); err != nil {
		t.Fatal(err)
	}
	if err = store.Store.Put(ctx, key, []byte("isolated lifecycle fixture"), "image/jpeg"); err != nil {
		t.Fatal(err)
	}
	makeOutputDue(t, pool, intent)
	results := make(chan error, 2)
	for i := 0; i < 2; i++ {
		go func() { _, err := sweeper.Reconcile(ctx, 100); results <- err }()
	}
	for i := 0; i < 2; i++ {
		if err := <-results; err != nil {
			t.Fatal(err)
		}
	}
	if store.deletes.Load() != 1 {
		t.Fatalf("concurrent cleanup count=%d", store.deletes.Load())
	}
	var checks int
	var code *string
	if err = pool.QueryRow(ctx, `SELECT cleanup_checks,last_error_code FROM generation_output_writes WHERE id=$1`, intent).Scan(&checks, &code); err != nil || checks != 3 || code != nil {
		t.Fatal(checks, code, err)
	}
}

func TestGenerationOutputEvidenceAndUpgradeGuards(t *testing.T) {
	pool, cleanup := testPool(t)
	defer cleanup()
	ctx := context.Background()
	owner := lifecycleOwner(t, pool)
	svc := creation.NewServiceWithRuntimes(pool, t.TempDir(), creation.NewRuntimeCatalog(newLifecycleRuntime(t)))
	g, err := svc.SubmitCommand(ctx, owner, creation.SubmitInput{Mode: "image", Prompt: "Protocol protected result"}, "protocol-output-test", "test")
	if err != nil {
		t.Fatal(err)
	}
	tx, err := pool.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback(ctx)
	if err = accountlifecycle.Lock(ctx, tx, owner); err != nil {
		t.Fatal(err)
	}
	if _, err = tx.Exec(ctx, `SELECT id FROM generations WHERE id=$1 FOR UPDATE`, g.ID); err != nil {
		t.Fatal(err)
	}
	intent, err := generationoutput.RegisterTx(ctx, tx, owner, g.ID, uuid.New(), media.NewLocalStore(t.TempDir()), []byte("owned bytes"), ".jpg")
	if err != nil {
		t.Fatal(err)
	}
	if err = tx.Commit(ctx); err != nil {
		t.Fatal(err)
	}
	for _, query := range []string{
		`DELETE FROM generation_output_writes WHERE id=$1`,
		`UPDATE generation_output_writes SET storage_key='other-key' WHERE id=$1`,
		`UPDATE generation_output_writes SET checksum_sha256=repeat('0',64) WHERE id=$1`,
		`UPDATE generation_output_writes SET status='attached',attached_at=now() WHERE id=$1`,
	} {
		if _, err = pool.Exec(ctx, query, intent.ID); err == nil {
			t.Fatal("unsafe journal mutation permitted", query)
		}
	}
	if _, err = pool.Exec(ctx, `UPDATE generations SET status='succeeded' WHERE id=$1`, g.ID); err == nil {
		t.Fatal("success without output binding")
	}
	down, err := os.ReadFile("../platform/database/migrations/0116_generation_output_journal.down.sql")
	if err != nil {
		t.Fatal(err)
	}
	gate, err := pool.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	_, err = gate.Exec(ctx, string(down))
	_ = gate.Rollback(ctx)
	if err == nil || !strings.Contains(err.Error(), "durable evidence") {
		t.Fatal("unsafe rollback", err)
	}
	// New binary declaration is mandatory on direct writers and all job claimers.
	old, err := pool.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = old.Exec(ctx, `SELECT set_config('app.generation_output_protocol','',true)`); err != nil {
		t.Fatal(err)
	}
	_, err = old.Exec(ctx, `UPDATE generations SET progress=1 WHERE id=$1`, g.ID)
	_ = old.Rollback(ctx)
	if err == nil || !strings.Contains(err.Error(), "generation-output-aware") {
		t.Fatal("old writer permitted", err)
	}
	old, err = pool.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = old.Exec(ctx, `SELECT set_config('app.generation_output_protocol','',true)`); err != nil {
		t.Fatal(err)
	}
	_, err = old.Exec(ctx, `UPDATE jobs SET status='running' WHERE kind='generation.generate' AND payload->>'generationId'=$1`, g.ID.String())
	_ = old.Rollback(ctx)
	if err == nil || !strings.Contains(err.Error(), "generation-output-aware") {
		t.Fatal("old worker permitted", err)
	}
}

func TestGenerationOutputInterruptedCleanupBacksOffAndEmitsMetrics(t *testing.T) {
	pool, cleanup := testPool(t)
	defer cleanup()
	ctx := context.Background()
	owner := lifecycleOwner(t, pool)
	store := &outputFaultStore{Store: media.NewLocalStore(t.TempDir()), afterPut: func() error { return errors.New("lost put response") }}
	catalog := media.NewCatalog(store)
	svc := creation.NewServiceWithMedia(pool, catalog, creation.NewRuntimeCatalog(newLifecycleRuntime(t)))
	g, err := svc.SubmitCommand(ctx, owner, creation.SubmitInput{Mode: "image", Prompt: "Interrupted cleanup"}, "interrupted-output-test", "test")
	if err != nil {
		t.Fatal(err)
	}
	job := lifecycleJob(t, pool, g.ID)
	job = testutil.FinalGenerationAttempt(t, pool, job)
	if err = svc.HandleJob(ctx, job); err == nil {
		t.Fatal("missing failure")
	}
	intent, key, _ := outputIntentFor(t, pool, g.ID)
	makeOutputDue(t, pool, intent)
	pass, cancel := context.WithCancel(ctx)
	defer cancel()
	store.deleteHook = func(ctx context.Context) error { cancel(); return ctx.Err() }
	sweeper := generationoutput.NewService(pool, catalog)
	if _, err = sweeper.Reconcile(pass, 100); !errors.Is(err, context.Canceled) {
		t.Fatal("interrupted cleanup ignored", err)
	}
	var code string
	var future bool
	if err = pool.QueryRow(ctx, `SELECT last_error_code,next_check_at>now() FROM generation_output_writes WHERE id=$1`, intent).Scan(&code, &future); err != nil || code != "generation_output_cleanup_failed" || !future {
		t.Fatalf("timeout can starve queue: %s %v %v", code, future, err)
	}
	metrics, err := observability.NewMetrics(time.Now()).Render(ctx, pool)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(metrics, "hcai_generation_output_cleanup_failed 1\n") || strings.Contains(metrics, key) || strings.Contains(metrics, owner.String()) {
		t.Fatal("unsafe or missing output failure metrics")
	}
	store.deleteHook = nil
	makeOutputDue(t, pool, intent)
	if _, err = sweeper.Reconcile(ctx, 100); err != nil {
		t.Fatal(err)
	}
	metrics, err = observability.NewMetrics(time.Now()).Render(ctx, pool)
	if err != nil || !strings.Contains(metrics, "hcai_generation_output_cleanup_failed 0\n") {
		t.Fatal("failure did not clear", err)
	}
}

func TestGenerationOutputJournalExportIsOwnerScopedAndOmitsLocators(t *testing.T) {
	pool, cleanup := testPool(t)
	defer cleanup()
	ctx := context.Background()
	root := t.TempDir()
	handle := "journal_" + uuid.NewString()[:8]
	owner, token, err := identity.NewRepository(pool).Register(ctx, identity.RegisterInput{Email: handle + "@test.local", Password: "local-test-password", Handle: handle, DisplayName: "Journal owner", Locale: "en-US", Timezone: "UTC"}, identity.ClientInfo{Label: "Output export test", RequestID: "test"})
	if err != nil {
		t.Fatal(err)
	}
	other := lifecycleOwner(t, pool)
	store := &outputFaultStore{Store: media.NewLocalStore(root), afterPut: func() error { return errors.New("lost put response") }}
	catalog := media.NewCatalog(store)
	svc := creation.NewServiceWithMedia(pool, catalog, creation.NewRuntimeCatalog(newLifecycleRuntime(t)))
	var keys []string
	var ownIntent, otherIntent uuid.UUID
	for _, user := range []uuid.UUID{owner.ID, other} {
		g, err := svc.SubmitCommand(ctx, user, creation.SubmitInput{Mode: "image", Prompt: "Export uncommitted output evidence"}, "export-output-evidence", "test")
		if err != nil {
			t.Fatal(err)
		}
		job := lifecycleJob(t, pool, g.ID)
		job = testutil.FinalGenerationAttempt(t, pool, job)
		if err = svc.HandleJob(ctx, job); err == nil {
			t.Fatal("expected failure")
		}
		id, key, _ := outputIntentFor(t, pool, g.ID)
		keys = append(keys, key)
		if user == owner.ID {
			ownIntent = id
		} else {
			otherIntent = id
		}
	}
	rights := datarights.NewServiceWithMedia(pool, root, catalog)
	request, err := rights.Create(ctx, owner.ID, token, datarights.CreateInput{RequestType: "data_export", IdentityConfirmation: owner.Handle}, "export-journal")
	if err != nil {
		t.Fatal(err)
	}
	payload, _ := json.Marshal(map[string]uuid.UUID{"requestId": request.ID})
	if err = rights.HandleExportJob(ctx, jobs.Job{Kind: datarights.ExportJobKind, Payload: payload}); err != nil {
		t.Fatal(err)
	}
	body, _, err := rights.Download(ctx, owner.ID, request.ID)
	if err != nil {
		t.Fatal(err)
	}
	var exported struct {
		Data map[string]json.RawMessage `json:"data"`
	}
	if err = json.Unmarshal(body, &exported); err != nil {
		t.Fatal(err)
	}
	var records []map[string]any
	if err = json.Unmarshal(exported.Data["generationOutputWrites"], &records); err != nil || len(records) != 1 || records[0]["id"] != ownIntent.String() || records[0]["status"] != "pending" {
		t.Fatal("incorrect owner projection", records, err)
	}
	if strings.Contains(string(body), otherIntent.String()) {
		t.Fatal("other owner journal disclosed")
	}
	for _, key := range keys {
		if strings.Contains(string(body), key) {
			t.Fatal("storage locator disclosed")
		}
	}
	for _, field := range []string{"storageKey", "storageBackend", "checksumSha256", "checksum_sha256"} {
		if _, ok := records[0][field]; ok {
			t.Fatal("private field disclosed", field)
		}
	}
}

func TestGenerationOutputMigrationDrainsWorkersAndRoundTripsEmptyJournal(t *testing.T) {
	pool, cleanup := testPool(t)
	defer cleanup()
	ctx := context.Background()
	down, err := os.ReadFile("../platform/database/migrations/0116_generation_output_journal.down.sql")
	if err != nil {
		t.Fatal(err)
	}
	up, err := os.ReadFile("../platform/database/migrations/0116_generation_output_journal.up.sql")
	if err != nil {
		t.Fatal(err)
	}
	tx, err := pool.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = tx.Exec(ctx, string(down)); err != nil {
		_ = tx.Rollback(ctx)
		t.Fatal(err)
	}
	if err = tx.Commit(ctx); err != nil {
		t.Fatal(err)
	}
	repo := jobs.NewRepository(pool)
	if _, err = repo.Enqueue(ctx, "test.output-drain", map[string]string{"scope": "isolated"}); err != nil {
		t.Fatal(err)
	}
	job, err := repo.Claim(ctx, "old-drained-worker", time.Minute)
	if err != nil {
		t.Fatal(err)
	}
	tx, err = pool.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	_, err = tx.Exec(ctx, string(up))
	_ = tx.Rollback(ctx)
	if err == nil || !strings.Contains(err.Error(), "drain running jobs") {
		t.Fatal("upgrade ignored active worker", err)
	}
	if err = repo.Complete(ctx, job, "old-drained-worker"); err != nil {
		t.Fatal(err)
	}
	tx, err = pool.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = tx.Exec(ctx, string(up)); err != nil {
		_ = tx.Rollback(ctx)
		t.Fatal(err)
	}
	if err = tx.Commit(ctx); err != nil {
		t.Fatal(err)
	}
	owner := lifecycleOwner(t, pool)
	svc := creation.NewServiceWithRuntimes(pool, t.TempDir(), creation.NewRuntimeCatalog(newLifecycleRuntime(t)))
	g, err := svc.SubmitCommand(ctx, owner, creation.SubmitInput{Mode: "image", Prompt: "Roundtrip protocol result"}, "journal-roundtrip-test", "test")
	if err != nil {
		t.Fatal(err)
	}
	if err = svc.HandleJob(ctx, lifecycleJob(t, pool, g.ID)); err != nil {
		t.Fatal(err)
	}
	_, _, state := outputIntentFor(t, pool, g.ID)
	if state != "attached" {
		t.Fatal(state)
	}
}

func TestGenerationOutputReservedLocationsCannotBeAdoptedOrRevived(t *testing.T) {
	pool, cleanup := testPool(t)
	defer cleanup()
	ctx := context.Background()
	owner := lifecycleOwner(t, pool)
	svc := creation.NewServiceWithRuntimes(pool, t.TempDir(), creation.NewRuntimeCatalog(newLifecycleRuntime(t)))
	g, err := svc.SubmitCommand(ctx, owner, creation.SubmitInput{Mode: "image", Prompt: "Reserved output location"}, "reserved-location-test", "test")
	if err != nil {
		t.Fatal(err)
	}
	store := &lifecycleStore{Store: media.NewLocalStore(t.TempDir())}
	catalog := media.NewCatalog(store)
	asset := uuid.New()
	tx, err := pool.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback(ctx)
	if err = accountlifecycle.Lock(ctx, tx, owner); err != nil {
		t.Fatal(err)
	}
	if _, err = tx.Exec(ctx, `SELECT id FROM generations WHERE id=$1 FOR UPDATE`, g.ID); err != nil {
		t.Fatal(err)
	}
	intent, err := generationoutput.RegisterTx(ctx, tx, owner, g.ID, asset, store, []byte("recorded result"), ".jpg")
	if err != nil {
		t.Fatal(err)
	}
	if err = tx.Commit(ctx); err != nil {
		t.Fatal(err)
	}
	insert := `INSERT INTO assets(id,owner_id,kind,title,media_url,mime_type,scan_status,source_type,source_id,license_code,storage_backend,storage_key)
 VALUES($1,$2,'image','Location adopter',$3,'image/jpeg','clean','generation',$4,'creator-owned',$5,$6)`
	if _, err = pool.Exec(ctx, insert, uuid.New(), owner, "/api/v1/assets/test/content", g.ID, intent.Backend, intent.Key); err == nil || !strings.Contains(err.Error(), "reserved generation output") {
		t.Fatal("another asset adopted pending output", err)
	}
	makeOutputDue(t, pool, intent.ID)
	if _, err = generationoutput.NewService(pool, catalog).Reconcile(ctx, 100); err != nil {
		t.Fatal(err)
	}
	if _, err = pool.Exec(ctx, insert, asset, owner, "/api/v1/assets/test/content", g.ID, intent.Backend, intent.Key); err == nil || !strings.Contains(err.Error(), "reserved generation output") {
		t.Fatal("retired output adopted", err)
	}
	tx, err = pool.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback(ctx)
	if err = accountlifecycle.Lock(ctx, tx, owner); err != nil {
		t.Fatal(err)
	}
	if _, err = tx.Exec(ctx, `SELECT id FROM generations WHERE id=$1 FOR UPDATE`, g.ID); err != nil {
		t.Fatal(err)
	}
	if err = generationoutput.WriteTx(ctx, tx, catalog, intent, []byte("recorded result"), "image/jpeg"); !errors.Is(err, generationoutput.ErrClosed) {
		t.Fatal("late writer was not fenced", err)
	}
	if store.puts.Load() != 0 {
		t.Fatal("late write reached store")
	}
}
