package community_test

import (
	"context"
	"errors"
	"github.com/hcai-chat/hcai-chat/internal/testutil"
	"net/url"
	"os"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/hcai-chat/hcai-chat/internal/admin"
	"github.com/hcai-chat/hcai-chat/internal/community"
	"github.com/hcai-chat/hcai-chat/internal/platform/database"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

func TestCommunityGovernanceLifecycle(t *testing.T) {
	pool, cleanup := governanceTestPool(t)
	defer cleanup()
	ctx := context.Background()
	moderatorID, authorID, reporterID := uuid.New(), uuid.New(), uuid.New()
	if _, err := pool.Exec(ctx, `
		INSERT INTO users(id,email,handle,display_name,role,status) VALUES
		($1,$2,$3,'Governance Moderator','moderator','active'),
		($4,$5,$6,'Community Author','creator','active'),
		($7,$8,$9,'Community Reporter','member','active')`,
		moderatorID, moderatorID.String()+"@test.local", "moderator_"+moderatorID.String()[:8],
		authorID, authorID.String()+"@test.local", "author_"+authorID.String()[:8],
		reporterID, reporterID.String()+"@test.local", "reporter_"+reporterID.String()[:8]); err != nil {
		t.Fatal(err)
	}
	assetID, workID, postID := uuid.New(), uuid.New(), uuid.New()
	if _, err := pool.Exec(ctx, `
		INSERT INTO assets(id,owner_id,kind,title,media_url,mime_type,scan_status,source_type,license_code)
		VALUES($1,$2,'image','Governed source','/media/governed.jpg','image/jpeg','clean','demo','demo')`, assetID, authorID); err != nil {
		t.Fatal(err)
	}
	if _, err := pool.Exec(ctx, `
		INSERT INTO works(id,author_id,asset_id,title,summary,model_name,status,ai_disclosure,published_at)
		VALUES($1,$2,$3,'Governed work','Integration test work','Local Test','published','Generated by deterministic Local Test provider.',now())`, workID, authorID, assetID); err != nil {
		t.Fatal(err)
	}
	if _, err := pool.Exec(ctx, `
		INSERT INTO posts(id,author_id,work_id,body,status,published_at)
		VALUES($1,$2,$3,'Governance lifecycle post','published',now())`, postID, authorID, workID); err != nil {
		t.Fatal(err)
	}

	repository := community.NewRepository(pool)
	comment, err := repository.CreateComment(ctx, reporterID, postID, "A specific and useful community response.")
	if err != nil || comment.AuthorID != reporterID {
		t.Fatalf("create comment: %#v %v", comment, err)
	}
	reaction, err := repository.SetReaction(ctx, reporterID, postID, "like", true)
	if err != nil || reaction.LikeCount != 1 || !reaction.ViewerLiked {
		t.Fatalf("set reaction: %#v %v", reaction, err)
	}
	follow, err := repository.SetFollow(ctx, reporterID, authorID, true)
	if err != nil || !follow.Following {
		t.Fatalf("set follow: %#v %v", follow, err)
	}
	posts, err := repository.ListForViewer(ctx, reporterID)
	if err != nil || len(posts) != 1 || posts[0].CommentCount != 1 || posts[0].LikeCount != 1 || !posts[0].ViewerFollowing {
		t.Fatalf("unexpected interaction inventory: %#v %v", posts, err)
	}

	report, err := repository.ReportPost(ctx, reporterID, postID, community.ReportInput{Category: "misleading", Details: "The disclosure requires a documented governance review."})
	if err != nil {
		t.Fatal(err)
	}
	var reportSignalCount, reportScore int
	if err := pool.QueryRow(ctx, `SELECT count(*),COALESCE(max(score),0) FROM risk_signals WHERE source_key=$1 AND signal_type='community_report' AND resource_type='post' AND subject_user_id=$2`, "community_report:"+report.ID.String(), authorID).Scan(&reportSignalCount, &reportScore); err != nil || reportSignalCount != 1 || reportScore != 35 {
		t.Fatalf("Community report risk evidence mismatch: count=%d score=%d err=%v", reportSignalCount, reportScore, err)
	}
	if _, err := repository.ReportPost(ctx, reporterID, postID, community.ReportInput{Category: "other", Details: "This duplicate open report must be rejected safely."}); !errors.Is(err, community.ErrConflict) {
		t.Fatalf("expected duplicate report conflict, got %v", err)
	}

	adminService := admin.NewService(pool, true)
	resolved, err := adminService.ResolveReport(ctx, moderatorID, report.ID, admin.ReportResolution{
		Outcome: "hidden",
	}, "request-governance-hide")
	if err != nil || resolved.Status != "resolved" || resolved.Outcome == nil || *resolved.Outcome != "hidden" {
		t.Fatalf("resolve report: %#v %v", resolved, err)
	}
	var workStatus, postStatus string
	if err := pool.QueryRow(ctx, `SELECT w.status,p.status FROM works w JOIN posts p ON p.work_id=w.id WHERE w.id=$1`, workID).Scan(&workStatus, &postStatus); err != nil {
		t.Fatal(err)
	}
	if workStatus != "hidden" || postStatus != "hidden" {
		t.Fatalf("moderation action not applied: work=%s post=%s", workStatus, postStatus)
	}

	cases, err := repository.ListMyReports(ctx, authorID, community.ReportListInput{})
	if err != nil || len(cases.Items) != 1 || !cases.Items[0].ViewerCanAppeal {
		t.Fatalf("author case inventory: %#v %v", cases, err)
	}
	appeal, err := repository.CreateAppeal(ctx, authorID, report.ID, "The disclosure is accurate and supporting provenance is available.")
	if err != nil {
		t.Fatal(err)
	}
	appealResult, err := adminService.ResolveAppeal(ctx, moderatorID, appeal.ID, admin.AppealResolution{
		Decision: "upheld",
	}, "request-governance-restore")
	if err != nil || appealResult.Status != "upheld" {
		t.Fatalf("resolve appeal: %#v %v", appealResult, err)
	}
	if err := pool.QueryRow(ctx, `SELECT w.status,p.status FROM works w JOIN posts p ON p.work_id=w.id WHERE w.id=$1`, workID).Scan(&workStatus, &postStatus); err != nil {
		t.Fatal(err)
	}
	if workStatus != "published" || postStatus != "published" {
		t.Fatalf("upheld appeal did not restore content: work=%s post=%s", workStatus, postStatus)
	}
	var governanceEvents, notifications int
	if err := pool.QueryRow(ctx, `SELECT count(*) FROM governance_events WHERE report_id=$1`, report.ID).Scan(&governanceEvents); err != nil {
		t.Fatal(err)
	}
	if err := pool.QueryRow(ctx, `SELECT count(*) FROM notifications WHERE user_id IN ($1,$2) AND kind LIKE 'community.%'`, authorID, reporterID).Scan(&notifications); err != nil {
		t.Fatal(err)
	}
	if governanceEvents != 4 || notifications < 5 {
		t.Fatalf("missing governance events or notifications: events=%d notifications=%d", governanceEvents, notifications)
	}
}

func TestCommunityReportHistoryPaginationAndIsolation(t *testing.T) {
	pool, cleanup := governanceTestPool(t)
	defer cleanup()
	ctx := context.Background()
	viewerID, subjectID, outsiderID := uuid.New(), uuid.New(), uuid.New()
	if _, err := pool.Exec(ctx, `
		INSERT INTO users(id,email,handle,display_name,role,status) VALUES
		($1,$2,$3,'History Viewer','member','active'),
		($4,$5,$6,'History Subject','creator','active'),
		($7,$8,$9,'History Outsider','member','active')`,
		viewerID, viewerID.String()+"@test.local", "history_viewer_"+viewerID.String()[:8],
		subjectID, subjectID.String()+"@test.local", "history_subject_"+subjectID.String()[:8],
		outsiderID, outsiderID.String()+"@test.local", "history_outsider_"+outsiderID.String()[:8]); err != nil {
		t.Fatal(err)
	}
	if _, err := pool.Exec(ctx, `
		INSERT INTO content_reports(reporter_id,resource_type,resource_id,subject_author_id,category,details,status,created_at,updated_at,resolved_at)
		SELECT $1,'comment',gen_random_uuid(),$2,'other','Paginated Community history '||value::text,'resolved',
		       now()-make_interval(secs=>value),now()-make_interval(secs=>value),now()-make_interval(secs=>value)
		FROM generate_series(1,206) value`, viewerID, subjectID); err != nil {
		t.Fatal(err)
	}
	if _, err := pool.Exec(ctx, `
		INSERT INTO content_reports(reporter_id,resource_type,resource_id,subject_author_id,category,details,status,resolved_at)
		VALUES($1,'comment',gen_random_uuid(),$1,'other','Invisible outsider history','resolved',now())`, outsiderID); err != nil {
		t.Fatal(err)
	}

	repository := community.NewRepository(pool)
	seen := make(map[uuid.UUID]struct{})
	cursor := ""
	for {
		page, err := repository.ListMyReports(ctx, viewerID, community.ReportListInput{Cursor: cursor, Limit: 50})
		if err != nil {
			t.Fatal(err)
		}
		for _, item := range page.Items {
			if _, duplicate := seen[item.ID]; duplicate {
				t.Fatalf("duplicate report %s", item.ID)
			}
			if item.ReporterID != viewerID && item.SubjectAuthorID != viewerID {
				t.Fatalf("invisible report leaked: %#v", item)
			}
			seen[item.ID] = struct{}{}
		}
		if page.NextCursor == nil {
			break
		}
		cursor = *page.NextCursor
	}
	if len(seen) != 206 {
		t.Fatalf("expected 206 visible reports, got %d", len(seen))
	}
	if _, err := repository.ListMyReports(ctx, viewerID, community.ReportListInput{Cursor: cursor + "modified", Limit: 50}); !errors.Is(err, community.ErrInvalidReportFilter) {
		t.Fatalf("modified report cursor was accepted: %v", err)
	}
	if _, err := repository.ListMyReports(ctx, viewerID, community.ReportListInput{Limit: 51}); !errors.Is(err, community.ErrInvalidReportFilter) {
		t.Fatalf("oversized report page was accepted: %v", err)
	}
}

func governanceTestPool(t *testing.T) (*pgxpool.Pool, func()) {
	t.Helper()
	ctx := context.Background()
	baseURL := os.Getenv("TEST_DATABASE_URL")
	if baseURL == "" {
		baseURL = "postgres://hcai:hcai@localhost:5432/hcai?sslmode=disable"
	}
	root, err := pgxpool.New(ctx, baseURL)
	if err != nil {
		testutil.DatabaseUnavailable(t, err)
	}
	if err := root.Ping(ctx); err != nil {
		root.Close()
		testutil.DatabaseUnavailable(t, err)
	}
	schema := "test_governance_" + uuid.NewString()[:8]
	if _, err := root.Exec(ctx, "CREATE SCHEMA "+pgx.Identifier{schema}.Sanitize()); err != nil {
		t.Fatal(err)
	}
	parsed, _ := url.Parse(baseURL)
	query := parsed.Query()
	query.Set("search_path", schema)
	parsed.RawQuery = query.Encode()
	pool, err := database.Open(ctx, parsed.String())
	if err != nil {
		t.Fatal(err)
	}
	if err := database.Migrate(ctx, pool); err != nil {
		t.Fatal(err)
	}
	return pool, func() {
		pool.Close()
		cleanupCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		_, _ = root.Exec(cleanupCtx, "DROP SCHEMA "+pgx.Identifier{schema}.Sanitize()+" CASCADE")
		root.Close()
	}
}
