package httpapi_test

import (
	"context"
	"io"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"net/url"
	"testing"

	"github.com/google/uuid"
	"github.com/hcai-chat/hcai-chat/internal/admin"
	"github.com/hcai-chat/hcai-chat/internal/community"
	"github.com/hcai-chat/hcai-chat/internal/identity"
	"github.com/hcai-chat/hcai-chat/internal/platform/config"
	"github.com/hcai-chat/hcai-chat/internal/transport/httpapi"
)

func TestCommunityGovernanceHTTPContract(t *testing.T) {
	pool, cleanup := httpTestPool(t)
	defer cleanup()
	server := httptest.NewServer(httpapi.New(config.Config{
		Environment: "test", MediaRoot: t.TempDir(), WebOrigin: "http://localhost:5173", LocalProviderEnabled: true,
	}, pool, slog.New(slog.NewTextHandler(io.Discard, nil))))
	defer server.Close()

	authorClient, reporterClient, adminClient := testHTTPClient(t), testHTTPClient(t), testHTTPClient(t)
	author := registerGovernanceUser(t, authorClient, server.URL, "author")
	reporter := registerGovernanceUser(t, reporterClient, server.URL, "reporter")
	administrator := registerGovernanceUser(t, adminClient, server.URL, "administrator")
	if _, err := pool.Exec(context.Background(), `UPDATE users SET role='admin' WHERE id=$1`, administrator.ID); err != nil {
		t.Fatal(err)
	}

	assetID, workID, postID := uuid.New(), uuid.New(), uuid.New()
	ctx := context.Background()
	if _, err := pool.Exec(ctx, `INSERT INTO assets(id,owner_id,kind,title,media_url,mime_type,scan_status,source_type,license_code) VALUES($1,$2,'image','HTTP governed asset','/media/http-governed.jpg','image/jpeg','clean','demo','demo')`, assetID, author.ID); err != nil {
		t.Fatal(err)
	}
	if _, err := pool.Exec(ctx, `INSERT INTO works(id,author_id,asset_id,title,summary,model_name,status,ai_disclosure,published_at) VALUES($1,$2,$3,'HTTP governed work','HTTP test','Local Test','published','Generated by deterministic Local Test provider.',now())`, workID, author.ID, assetID); err != nil {
		t.Fatal(err)
	}
	if _, err := pool.Exec(ctx, `INSERT INTO posts(id,author_id,work_id,body,status,published_at) VALUES($1,$2,$3,'HTTP governance post','published',now())`, postID, author.ID, workID); err != nil {
		t.Fatal(err)
	}

	var report community.Report
	response := requestJSON(t, reporterClient, http.MethodPost, server.URL+"/api/v1/community/posts/"+postID.String()+"/reports", map[string]any{
		"category": "misleading", "details": "The disclosure needs a documented HTTP governance review.",
	}, &report)
	if response.StatusCode != http.StatusCreated || report.ReporterID != reporter.ID {
		t.Fatalf("report contract failed: status=%d report=%#v", response.StatusCode, report)
	}
	response = requestJSON(t, reporterClient, http.MethodGet, server.URL+"/api/v1/admin/governance/reports", nil, nil)
	if response.StatusCode != http.StatusForbidden {
		t.Fatalf("member accessed governance queue: %d", response.StatusCode)
	}

	var queue struct {
		Items []admin.GovernanceReport `json:"items"`
	}
	response = requestJSON(t, adminClient, http.MethodGet, server.URL+"/api/v1/admin/governance/reports", nil, &queue)
	if response.StatusCode != http.StatusOK || len(queue.Items) != 1 || queue.Items[0].ID != report.ID {
		t.Fatalf("admin report queue failed: status=%d items=%#v", response.StatusCode, queue.Items)
	}
	var resolved admin.GovernanceReport
	response = requestJSON(t, adminClient, http.MethodPost, server.URL+"/api/v1/admin/governance/reports/"+report.ID.String()+"/resolve", map[string]any{
		"outcome": "hidden",
	}, &resolved)
	if response.StatusCode != http.StatusOK || resolved.Status != "resolved" || resolved.Outcome == nil || *resolved.Outcome != "hidden" {
		t.Fatalf("admin report resolution failed: status=%d report=%#v", response.StatusCode, resolved)
	}

	var cases struct {
		Items []community.Report `json:"items"`
	}
	response = requestJSON(t, authorClient, http.MethodGet, server.URL+"/api/v1/community/reports/mine", nil, &cases)
	if response.StatusCode != http.StatusOK || len(cases.Items) != 1 || !cases.Items[0].ViewerCanAppeal {
		t.Fatalf("subject case inventory failed: status=%d items=%#v", response.StatusCode, cases.Items)
	}
	var appeal community.Appeal
	response = requestJSON(t, authorClient, http.MethodPost, server.URL+"/api/v1/community/reports/"+report.ID.String()+"/appeals", map[string]any{
		"reason": "The attached provenance supports the published disclosure and restoration.",
	}, &appeal)
	if response.StatusCode != http.StatusCreated || appeal.AppellantID != author.ID {
		t.Fatalf("appeal contract failed: status=%d appeal=%#v", response.StatusCode, appeal)
	}
	var appealResult admin.GovernanceAppeal
	response = requestJSON(t, adminClient, http.MethodPost, server.URL+"/api/v1/admin/governance/appeals/"+appeal.ID.String()+"/resolve", map[string]any{
		"decision": "upheld",
	}, &appealResult)
	if response.StatusCode != http.StatusOK || appealResult.Status != "upheld" {
		t.Fatalf("admin appeal resolution failed: status=%d appeal=%#v", response.StatusCode, appealResult)
	}
	var workStatus, postStatus string
	if err := pool.QueryRow(ctx, `SELECT w.status,p.status FROM works w JOIN posts p ON p.work_id=w.id WHERE w.id=$1`, workID).Scan(&workStatus, &postStatus); err != nil {
		t.Fatal(err)
	}
	if workStatus != "published" || postStatus != "published" {
		t.Fatalf("upheld appeal did not restore HTTP resource: work=%s post=%s", workStatus, postStatus)
	}
}

func TestCommunityReportHistoryHTTPPagination(t *testing.T) {
	pool, cleanup := httpTestPool(t)
	defer cleanup()
	server := httptest.NewServer(httpapi.New(config.Config{
		Environment: "test", MediaRoot: t.TempDir(), WebOrigin: "http://localhost:5173", LocalProviderEnabled: true,
	}, pool, slog.New(slog.NewTextHandler(io.Discard, nil))))
	defer server.Close()

	viewerClient, subjectClient := testHTTPClient(t), testHTTPClient(t)
	viewer := registerGovernanceUser(t, viewerClient, server.URL, "history_viewer")
	subject := registerGovernanceUser(t, subjectClient, server.URL, "history_subject")
	ctx := context.Background()
	if _, err := pool.Exec(ctx, `
		INSERT INTO content_reports(reporter_id,resource_type,resource_id,subject_author_id,category,details,status,created_at,updated_at,resolved_at)
		SELECT $1,'comment',gen_random_uuid(),$2,'other','HTTP paginated Community history '||value::text,'resolved',
		       now()-make_interval(secs=>value),now()-make_interval(secs=>value),now()-make_interval(secs=>value)
		FROM generate_series(1,56) value`, viewer.ID, subject.ID); err != nil {
		t.Fatal(err)
	}

	type reportPage struct {
		Items      []community.Report `json:"items"`
		NextCursor *string            `json:"nextCursor"`
	}
	seen := make(map[uuid.UUID]struct{})
	cursor := ""
	for pageNumber := 0; ; pageNumber++ {
		endpoint := server.URL + "/api/v1/community/reports/mine?limit=20"
		if cursor != "" {
			endpoint += "&cursor=" + url.QueryEscape(cursor)
		}
		var page reportPage
		response := requestJSON(t, viewerClient, http.MethodGet, endpoint, nil, &page)
		if response.StatusCode != http.StatusOK {
			t.Fatalf("history page %d returned %d", pageNumber+1, response.StatusCode)
		}
		for _, item := range page.Items {
			if _, duplicate := seen[item.ID]; duplicate {
				t.Fatalf("duplicate HTTP report %s", item.ID)
			}
			seen[item.ID] = struct{}{}
		}
		if page.NextCursor == nil {
			break
		}
		cursor = *page.NextCursor
	}
	if len(seen) != 56 {
		t.Fatalf("expected 56 HTTP reports, got %d", len(seen))
	}
	response := requestJSON(t, viewerClient, http.MethodGet, server.URL+"/api/v1/community/reports/mine?cursor="+url.QueryEscape(cursor+"modified"), nil, nil)
	if response.StatusCode != http.StatusUnprocessableEntity {
		t.Fatalf("modified HTTP cursor accepted: %d", response.StatusCode)
	}
	response = requestJSON(t, viewerClient, http.MethodGet, server.URL+"/api/v1/community/reports/mine?limit=51", nil, nil)
	if response.StatusCode != http.StatusUnprocessableEntity {
		t.Fatalf("oversized HTTP page accepted: %d", response.StatusCode)
	}
}

func registerGovernanceUser(t *testing.T, client *http.Client, serverURL, prefix string) identity.User {
	t.Helper()
	var result struct {
		User identity.User `json:"user"`
	}
	value := uuid.NewString()[:8]
	response := requestJSON(t, client, http.MethodPost, serverURL+"/api/v1/auth/register", map[string]any{
		"email": prefix + "-" + value + "@test.local", "password": "correct-horse-2026", "handle": prefix + "_" + value,
		"displayName": prefix + " governance", "locale": "en-US", "timezone": "UTC",
	}, &result)
	if response.StatusCode != http.StatusCreated {
		t.Fatalf("register %s: %d", prefix, response.StatusCode)
	}
	return result.User
}
